name: GrimAC
version: 0.0.2
main: ac.grim.grimac.GrimAC
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
api-version: 1.13
load: POSTWORLD
permissions:
  grim.alerts:
    description: Receieve alerts for violations
    default: op
  grim.performance:
    description: Check performance metrics
    default: op